CONTAINER Opycurl
{
	NAME Opycurl;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES {
		REAL SPEED  { MIN 0; MAX 1000;STEP 0.1;}
		REAL NOISESCALE { MIN 0; MAX 1000; STEP 0.1;}
		REAL DISP { MIN 0; MAX 1000; STEP 0.1;}

	}

	
}
